"""Agregar campo contrasena a Cliente

Revision ID: 0b17006ec0e1
Revises: 934ad5cb652f
Create Date: 2025-07-22 19:39:39.770235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b17006ec0e1'
down_revision = '934ad5cb652f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contrasena', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('contrasena')

    # ### end Alembic commands ###
