"""Inicial

Revision ID: 934ad5cb652f
Revises: 
Create Date: 2025-07-22 19:32:18.019559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934ad5cb652f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurante',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('horario_apertura', sa.String(length=10), nullable=True),
    sa.Column('horario_cierre', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesa.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurante.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva')
    op.drop_table('mesa')
    op.drop_table('foto')
    op.drop_table('comentario')
    op.drop_table('restaurante')
    op.drop_table('cliente')
    # ### end Alembic commands ###
